export enum Roles {
  kiosk = 'kiosk',
  orders = 'orders',
  management_production = 'management_production',
  production_summary = 'production_summary',
  production_wood = 'production_wood',
  production_metal = 'production_metal',
  production_paint = 'production_paint',
  production_glass = 'production_glass',
  production_marble = 'production_marble',
  production_fabric = 'production_fabric',
  packaging = 'packaging',
  shipment_summary = 'shipment_summary',
  shipment_shipmentOrder = 'shipment_shipmentOrder',
  shipment_shipmentManagement = 'shipment_shipmentManagement',
  shipment_invoice = 'shipment_invoice',
  log = 'log',
  oem = 'oem',
  return_cancel = 'return_cancel',
  admin = 'admin',
}
