export enum Roles {
  kiosk = 'kiosk',
  orders = 'orders',
  management_production = 'management_production',
  production_summary = 'production_summary',
  production_wood = 'production_wood',
  production_metal = 'production_metal',
  production_paint = 'production_paint',
  production_glass = 'production_glass',
  production_marble = 'production_marble',
  production_fabric = 'production_fabric',
  packaging = 'packaging',
  shipment_summary = 'shipment_summary',
  shipment_shipmentOrder = 'shipment_shipmentOrder',
  shipment_shipmentManagement = 'shipment_shipmentManagement',
  shipment_invoice = 'shipment_invoice',
  log = 'log',
  oem = 'oem',
  return_cancel = 'return_cancel',
  admin = 'admin',
}

export const RoleTexts = {
  [Roles.admin]: 'Admin',
  [Roles.kiosk]: 'Kiosk',
  [Roles.management_production]: 'Üretim Yönetimi',
  [Roles.production_summary]: 'Üretim Özeti',
  [Roles.production_wood]: 'Ahşap Atölyesi',
  [Roles.production_metal]: 'Metal Atölyesi',
  [Roles.production_paint]: 'Boya Atölyesi',
  [Roles.production_marble]: 'Mermer Atölyesi',
  [Roles.production_glass]: 'Cam Atölyesi',
  [Roles.production_fabric]: 'Kumaş Atölyesi',
  [Roles.packaging]: 'Toplama/Paketleme',
  [Roles.return_cancel]: 'İptal/İade',
  [Roles.shipment_invoice]: 'Sevkiyat/Fatura',
  [Roles.shipment_shipmentManagement]: 'Sevkiyat Yönetimi',
  [Roles.shipment_shipmentOrder]: 'Sevkiyat',
  [Roles.shipment_summary]: 'Sevkiyat Özeti',
  [Roles.log]: 'Loglar',
  [Roles.oem]: 'Al-Sat',
  [Roles.orders]: 'Siparişler',
};
